### ISSUE TITLE
Support egui 0.28.0+

### ISSUE THREAD

**Issue by red-avtovo** [zeozeozeo/egui-twemoji#1]
Hi! Thanks for your library!
The new egui 0.28.0 version migrated the `Ui` type away from `egui:ui:Ui` what makes the library incompatible. Could you please update the library so it complies with the latest packaging

<img width="942" alt="image" src="https://github.com/user-attachments/assets/48dc6c01-b779-4a44-ad2c-cffa07f5cefb">

**Comment by luadebug** [comment]
Yes pretty please. Update it. 😔😔😔 
![image](https://github.com/user-attachments/assets/c8feeba9-68eb-4df0-b5f6-82091581d9cb)
I have made pull request, hope it will be resolved soon.
#2

**Comment by zeozeozeo** [comment]
Closed by #2
